### ISSUE TITLE
refetchWhen not called during navigation

### ISSUE THREAD

**Issue by RJN368** [djgrant/redux-quest#2]
I've been using this module to provide lazy loading of data into a redux store, everything is working as I'd hope but I am having trouble making refetchWhen work on page navigation changes.  I have 2 scenarios one where the data needs to be refreshed when a user navigates away from the page and one where the data needs to be refreshed on a time basis.  Any help appreciated.

**Comment by djgrant** [comment]
`refetchWhen` is only called with [componentWillReceiveProps](https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops) i.e. when new props are being passed to the component, so to make use of this method you need new props to get passed to the component on the navigation events you are targeting. 

I haven't thought too deeply about this but if you're using react-router I'm guessing something like this could work:

```js
compose(
  withRouter,
  quest({
    resolver: yourResolver,
    refetchWhen: (props, nextProps) => props.location !== nextProps.location
  })
)
```
